server:
  port: 8091
  
spring:
  cloud:
    consul:
      host: consul.development.svc.cluster.local
      port: 8500
      healthCheckPath: metric/health
      
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG