server:
  port: 8091
  
spring:
  cloud:
    consul:
      host: consul.development.svc.cluster.local
      port: 8500
      healthCheckPath: metric/health
    rabbitmq:
      host: 192.168.0.16
      port: 5672
      username: guest
      password: guest
      
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG