server:
  port: 9000
  
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

zuul:
  include-debug-header: true
  trace-request-body: true
  routes:
    user:
      path: /account/**
      stripPrefix: false
      serviceId: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
    