server:
  port: 9000
  
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

zuul:
  include-debug-header: true
  trace-request-body: true
  prefix: /api
  routes:
    account-service:
      path: /account/**
      serviceId: account-service
    customer-service:
      path: /customer/**
      serviceId: customer-service
    order-service:
      path: /order/**
      serviceId: order-service
    product-service:
      path: /product/**
      serviceId: product-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://hyunwoo-kim.iptime.org:32002/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
    