server:
  port: 8092
  ssl:
    enabled: true
    key-store: classpath:customer.jks
    key-store-password: 1q2w3e4r5t!
    key-alias: customer
    
security:
  require-ssl: true

spring:
  rabbitmq:
    host: 192.168.0.16
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    securePortEnabled: true
    service-url:
      defaultZone: https://eureka.development.svc.cluster.local:32002/eureka/
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 8092
    statusPageUrl: https://eureka.development.svc.cluster.local:${eureka.instance.securePort}/info
    healthCheckUrl: https://eureka.development.svc.cluster.local:${eureka.instance.securePort}/health
    homePageUrl: https://eureka.development.svc.cluster.local:${eureka.instance.securePort}/
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5