server:
  port: 8090
  
spring:
  rabbitmq:
    host: 192.168.0.16
    port: 5672
    username: guest
    password: guest
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.development.svc.cluster.local:32002/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5